# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PingBYiDVS3XhWYvL2X9N7AovZsOWwNb
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("data/jobs.csv")

st.title("Real-Time Job Market Dashboard")


st.subheader("Sample Job Listings")
st.dataframe(df.head())

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['summary'])
word_counts = X.sum(axis=0).A1
words = vectorizer.get_feature_names_out()


freq_df = pd.DataFrame({'word': words, 'count': word_counts})
freq_df = freq_df.sort_values(by="count", ascending=False).head(20)

st.subheader("Top Keywords in Job Descriptions")
st.bar_chart(freq_df.set_index('word'))

st.success("✅ Dashboard loaded successfully!")