# -*- coding: utf-8 -*-
"""job_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PingBYiDVS3XhWYvL2X9N7AovZsOWwNb
"""

import requests
import pandas as pd

APP_ID = "460ecddf"
APP_KEY = "7a4521a9e26eb8340c4b65bce0f06e5b"

def scrape_adzuna_jobs(country="in", results_per_page=20, pages=2):
    base_url = f"https://api.adzuna.com/v1/api/jobs/{country}/search/"
    job_data = []

    for page in range(1, pages + 1):
        url = f"{base_url}{page}?app_id={APP_ID}&app_key={APP_KEY}&results_per_page={results_per_page}&what=data scientist&where=India&content-type=application/json"

        response = requests.get(url)
        if response.status_code != 200:
            print("❌ Failed to fetch data:", response.status_code)
            continue

        results = response.json().get("results", [])
        for job in results:
            job_data.append({
                "title": job.get("title", ""),
                "company": job.get("company", {}).get("display_name", ""),
                "location": job.get("location", {}).get("display_name", ""),
                "summary": job.get("title", "") + " at " + job.get("company", {}).get("display_name", "")
 
            })

    df = pd.DataFrame(job_data)
    df.to_csv("data/jobs.csv", index=False)
    print(f"✅ Scraped {len(df)} jobs from Adzuna API.")
    return df

if __name__ == "__main__":
    scrape_adzuna_jobs()